// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tylnagxldzcxiviurcgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bG5hZ3hsZHpjeGl2aXVyY2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjI2OTksImV4cCI6MjA3MDI5ODY5OX0.SUJ44Nn4ubxHCiLN511fmty-W0FjZBt92qSWVkk2dl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});